# Generated by Django 3.0.14 on 2021-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pneumatiky',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typ', models.IntegerField()),
                ('znacka', models.CharField(blank=True, max_length=50, null=True)),
                ('rozmery', models.CharField(max_length=30)),
                ('hloubka_dezenu', models.IntegerField()),
                ('sjete', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Pneumatiky',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServisPracovnik',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=10)),
                ('datum_narozeni', models.DateField(blank=True, null=True)),
                ('telefon', models.IntegerField()),
            ],
            options={
                'db_table': 'Servis_pracovnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServisZaznam',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datum', models.DateTimeField()),
            ],
            options={
                'db_table': 'Servis_zaznam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('skladid', models.IntegerField(db_column='skladID', primary_key=True, serialize=False)),
                ('pocet', models.IntegerField()),
                ('misto_uskladneni', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sklad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypServis',
            fields=[
                ('typid', models.AutoField(db_column='typID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Typ_servis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypVozidla',
            fields=[
                ('typvozidlaid', models.IntegerField(db_column='typVozidlaID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Typ_vozidla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypZakaznik',
            fields=[
                ('typzakaznikid', models.IntegerField(db_column='typZakaznikID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=40)),
                ('registrovany', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Typ_zakaznik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vozidlo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('znacka', models.CharField(blank=True, max_length=50, null=True)),
                ('spz', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'Vozidlo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('adresa', models.CharField(blank=True, max_length=40, null=True)),
                ('telefon', models.IntegerField()),
                ('login', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Zakaznik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZakaznikVozidloRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Zakaznik_Vozidlo_Relation',
                'managed': False,
            },
        ),
    ]
